2025-07-29 22:35:10,423 - DEBUG - wrapper:342 - matplotlib data path: D:\Python\SnakeTkinter\.venv\lib\site-packages\matplotlib\mpl-data
2025-07-29 22:35:10,433 - DEBUG - wrapper:342 - CONFIGDIR=C:\Users\user\.matplotlib
2025-07-29 22:35:10,436 - DEBUG - <module>:1557 - interactive is False
2025-07-29 22:35:10,436 - DEBUG - <module>:1558 - platform is win32
2025-07-29 22:35:10,512 - DEBUG - wrapper:342 - CACHEDIR=C:\Users\user\.matplotlib
2025-07-29 22:35:10,516 - DEBUG - _load_fontmanager:1635 - Using fontManager instance from C:\Users\user\.matplotlib\fontlist-v390.json
2025-07-29 22:35:18,852 - INFO - log_user_action:63 - User Action: mode_changed - {'old_mode': 'ai_battle', 'new_mode': 'ai_battle'}
2025-07-29 22:35:23,538 - ERROR - log_error:50 - Error: 'GameModeManager' object has no attribute 'check_ai_battle_conditions' - Context: Game loop error
2025-07-29 22:35:23,540 - ERROR - log_error:51 - Traceback: Traceback (most recent call last):
  File "D:\Python\SnakeTkinter\main.py", line 1348, in game_loop
    mode_conditions = game_mode_manager.check_mode_conditions(game_state)
  File "D:\Python\SnakeTkinter\game_modes.py", line 245, in check_mode_conditions
    battle_result = self.check_ai_battle_conditions(game_state)
AttributeError: 'GameModeManager' object has no attribute 'check_ai_battle_conditions'

2025-07-29 22:35:28,444 - ERROR - log_error:50 - Error: 'GameModeManager' object has no attribute 'check_ai_battle_conditions' - Context: Game loop error
2025-07-29 22:35:28,445 - ERROR - log_error:51 - Traceback: Traceback (most recent call last):
  File "D:\Python\SnakeTkinter\main.py", line 1348, in game_loop
    mode_conditions = game_mode_manager.check_mode_conditions(game_state)
  File "D:\Python\SnakeTkinter\game_modes.py", line 245, in check_mode_conditions
    battle_result = self.check_ai_battle_conditions(game_state)
AttributeError: 'GameModeManager' object has no attribute 'check_ai_battle_conditions'

2025-07-29 22:35:29,997 - ERROR - log_error:50 - Error: 'GameModeManager' object has no attribute 'check_ai_battle_conditions' - Context: Game loop error
2025-07-29 22:35:29,999 - ERROR - log_error:51 - Traceback: Traceback (most recent call last):
  File "D:\Python\SnakeTkinter\main.py", line 1348, in game_loop
    mode_conditions = game_mode_manager.check_mode_conditions(game_state)
  File "D:\Python\SnakeTkinter\game_modes.py", line 245, in check_mode_conditions
    battle_result = self.check_ai_battle_conditions(game_state)
AttributeError: 'GameModeManager' object has no attribute 'check_ai_battle_conditions'

2025-07-29 22:35:31,661 - ERROR - log_error:50 - Error: 'GameModeManager' object has no attribute 'check_ai_battle_conditions' - Context: Game loop error
2025-07-29 22:35:31,662 - ERROR - log_error:51 - Traceback: Traceback (most recent call last):
  File "D:\Python\SnakeTkinter\main.py", line 1348, in game_loop
    mode_conditions = game_mode_manager.check_mode_conditions(game_state)
  File "D:\Python\SnakeTkinter\game_modes.py", line 245, in check_mode_conditions
    battle_result = self.check_ai_battle_conditions(game_state)
AttributeError: 'GameModeManager' object has no attribute 'check_ai_battle_conditions'

2025-07-29 22:35:32,291 - ERROR - log_error:50 - Error: 'GameModeManager' object has no attribute 'check_ai_battle_conditions' - Context: Game loop error
2025-07-29 22:35:32,293 - ERROR - log_error:51 - Traceback: Traceback (most recent call last):
  File "D:\Python\SnakeTkinter\main.py", line 1348, in game_loop
    mode_conditions = game_mode_manager.check_mode_conditions(game_state)
  File "D:\Python\SnakeTkinter\game_modes.py", line 245, in check_mode_conditions
    battle_result = self.check_ai_battle_conditions(game_state)
AttributeError: 'GameModeManager' object has no attribute 'check_ai_battle_conditions'

2025-07-29 22:35:33,125 - INFO - log_game_event:45 - Game Event: game_restart - {'score': 0}
